// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCR2kS9iZIs9W8az2SLF7eiqLqIBhFAwUA',
    appId: '1:395130436459:web:be874f1d01e95cec0daa2e',
    messagingSenderId: '395130436459',
    projectId: 'projectuas-96da9',
    authDomain: 'projectuas-96da9.firebaseapp.com',
    storageBucket: 'projectuas-96da9.firebasestorage.app',
    measurementId: 'G-JFKX21Q1PB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCshH2RJs7urMCdLm1pu9K3Jd1K7mk8Grc',
    appId: '1:395130436459:android:c5ddcde8fe2b48a40daa2e',
    messagingSenderId: '395130436459',
    projectId: 'projectuas-96da9',
    storageBucket: 'projectuas-96da9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvj_puofOk2pfcq_6-mWq-1Zf8t6EFUn0',
    appId: '1:395130436459:ios:09ca4a60da21780c0daa2e',
    messagingSenderId: '395130436459',
    projectId: 'projectuas-96da9',
    storageBucket: 'projectuas-96da9.firebasestorage.app',
    iosBundleId: 'com.example.projectUas',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDvj_puofOk2pfcq_6-mWq-1Zf8t6EFUn0',
    appId: '1:395130436459:ios:09ca4a60da21780c0daa2e',
    messagingSenderId: '395130436459',
    projectId: 'projectuas-96da9',
    storageBucket: 'projectuas-96da9.firebasestorage.app',
    iosBundleId: 'com.example.projectUas',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCR2kS9iZIs9W8az2SLF7eiqLqIBhFAwUA',
    appId: '1:395130436459:web:ffe2661bcadb72de0daa2e',
    messagingSenderId: '395130436459',
    projectId: 'projectuas-96da9',
    authDomain: 'projectuas-96da9.firebaseapp.com',
    storageBucket: 'projectuas-96da9.firebasestorage.app',
    measurementId: 'G-3VPQ7TFELK',
  );
}
